services:

  db:
    image: postgres:14.5
    restart: always
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:7.0.4
    restart: always
    volumes:
    - ./data/cache:/data

  web:
    build: .  # look for a Dockerfile at this location
    command: ["/code/wait-for-it.sh", "db:5432", "--",
              "python", "/code/manage.py", "runserver", "0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ELearningPlatform.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:  #  depends_on dependency. The web service is started after the db service.
      - db
      - cache
